---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-control-plane
  labels:
    app: go-control-plane
spec:
  replicas: 1
  selector:
    matchLabels:
      app: go-control-plane
  template:
    metadata:
      labels:
        app: go-control-plane
    spec:
      containers:
      - name: go-control-plane
        image: go-control-plane
        #image: go-control-plane:ae121f7f4c92beb74930b331dc5dd9d0948cacb9126d490ea06477ebc6cd0d4f
---
apiVersion: v1
kind: Service
metadata:
  name: envoy-xds # xds-service
spec:
  selector:
    app: go-control-plane
  ports:
    - protocol: TCP
      port: 18000
      targetPort: 18000
---
apiVersion: v1
kind: Service
metadata:
  name: xds-service
spec:
  selector:
    app: go-control-plane
  ports:
    - protocol: TCP
      port: 18000
      targetPort: 18000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy
  labels:
    app: envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: envoy
  template:
    metadata:
      labels:
        app: envoy
    spec:
      containers:
      - name: envoy
        image: envoy
        #image: envoy:3ffbe55d92689a7beae3182a186811802a207d5df84233f836bac569c3b14aff